import "reflect-metadata";
import {createConnection} from "typeorm"
import * as salting from "./src/bin/salting"
import {User, UserRole} from "./src/entity/User"
import {Order} from "./src/entity/Order"
import {Equipment, EquipmentType, TyreType, Brand} from "./src/entity/Equipment"

createConnection().then(async connection => {

    connection.createQueryBuilder().insert().into(User).values([
        {
            firstName: "Andrzej",
            lastName: "Bąk",
            email: "andrzej.bak@janusze.pl",
            phone_number: "962021207",
            post_code: "32-663",
            place: "Rzepiennik Strzyżewski",
            address: "6 Buell Way",
            password: salting.getSaltedPassword("30m8CnBxyY"),
            orders: null,
            role: UserRole.CLIENT
        },
        {
            firstName: "Wojciech",
            lastName: "Czerwiec",
            email: "wojciech.czerwiec@roksa.pl",
            phone_number: "543860237",
            post_code: "23-363",
            place: "Jajar",
            address: "50302 Schiller Terrace",
            password: salting.getSaltedPassword("xhjmJG1TtLGO"),
            orders: null,
            role: UserRole.CLIENT,
        },
        {
            firstName: "Tytus",
            lastName: "Bomba",
            email: "tytus.bomba@gwiezdnaflota.pl",
            phone_number: "493751241",
            post_code: "83-163",
            place: "Barayong",
            address: "8 Golf View Junction",
            password: salting.getSaltedPassword("E3qdsgfUaB"),
            orders: null,
            role: UserRole.CLIENT,
        },
        {
            firstName: "Piotruś",
            lastName: "Lach",
            email: "piotr.lach@onet.pl",
            phone_number: "762056467",
            post_code: "32-663",
            place: "Rzepiennik Strzyżewski",
            address: "9 Dwight Crossing",
            password: salting.getSaltedPassword("R23nwE7tO"),
            orders: null,
            role: UserRole.CLIENT,
        },
        {
            firstName: "Cezary",
            lastName: "Boczek",
            email: "cezary.boczek@janusze.pl",
            phone_number: "702203293",
            post_code: "13-563",
            place: "Kishorganj",
            address: "20989 Upham Terrace",
            password: salting.getSaltedPassword("zSiPWk2QdZv"),
            orders: null,
            role: UserRole.CLIENT
        },
        {
            firstName: "Mateusz",
            lastName: "Rudy",
            email: "mecze.jsa@kochamjave.com",
            phone_number: "953523704",
            post_code: "94-063",
            place: "Jembangan",
            address: "6582 Grover Center",
            password: salting.getSaltedPassword("cex213Aj9jB"),
            orders: null,
            role: UserRole.CLIENT
        },
        {
            firstName: "Spok",
            lastName: "Spoooook",
            email: "dobry.kolega@startrek.pl",
            phone_number: "115839482",
            post_code: "52-363",
            place: "Gimcheon",
            address: "09613 Village Green Road",
            password: salting.getSaltedPassword("ZQx3adsWFY"),
            orders: null,
            role: UserRole.CLIENT
        },
        {
            firstName: "Zenek",
            lastName: "Stonoga",
            email: "zenus@niezalezny.org",
            phone_number: "320361194",
            post_code: "15-963",
            place: "Bugko",
            address: "1190 Norway Maple Way",
            password: salting.getSaltedPassword("dBc12SL6eq"),
            orders: null,
            role: UserRole.CLIENT
        },
        {
            firstName: "Ojciec",
            lastName: "Rydz",
            email: "rudyrydz@parafia.cc",
            phone_number: "349712962",
            post_code: "72-263",
            place: "Uralo-Kavkaz",
            address: "4 Washington Plaza",
            password: salting.getSaltedPassword("uoYGdsa2NHeiSe9"),
            orders: null,
            role: UserRole.CLIENT
        },
        {
            firstName: "Przemek",
            lastName: "Rak",
            email: "smierdzacylen@wp.pl",
            phone_number: "192076577",
            post_code: "12-563",
            place: "San Onofre",
            address: "2839 Dahle Lane",
            password: salting.getSaltedPassword("Arl5DmpUP9"),
            orders: null,
            role: UserRole.ADMIN
        },
    ]).execute();

   connection.createQueryBuilder().insert().into(Equipment).values([
        {
            equipment_type:EquipmentType.TRACTOR,
            tyre_type: TyreType.R1,
            model: "Major 80",
            cost_per_day: 590.00,
            fuel_capacity: 83,
            horsepower: 75,
            mass: 3078,
            max_speed: 33,
            brand: Brand.ZETOR,
            orders: null,
        },
        {
            equipment_type: EquipmentType.TRACTOR,
            tyre_type: TyreType.R2,
            model: "700 Vario",
            cost_per_day: 1640.00,
            fuel_capacity: 400,
            horsepower: 165,
            mass: 8006,
            max_speed: 53,
            brand: Brand.FENDT,
            orders: null,
        },
        {
            equipment_type: EquipmentType.TRACTOR,
            tyre_type: TyreType.R3,
            model: "MF 7700",
            cost_per_day: 1720.00,
            fuel_capacity: 430,
            horsepower: 210,
            mass: 7540,
            max_speed: 53,
            brand: Brand.MASSEY_FERGUSON,
            orders: null,
        },
        {
            equipment_type: EquipmentType.HARVESTER,
            tyre_type: TyreType.R4,
            model: "TC5.90",
            working_width: 9,
            cost_per_day: 1760.00,
            crop_capacity: 6400,
            fuel_capacity: 400,
            horsepower: 258,
            mass: 11809,
            max_speed: 23,
            brand: Brand.NEW_HOLLAND,
            orders: null,
        },
        {
            equipment_type: EquipmentType.HARVESTER,
            tyre_type: TyreType.R4,
            model: "1660 Axial-Flow",
            working_width: 6,
            cost_per_day: 1450.00,
            crop_capacity: 6340,
            fuel_capacity: 350,
            horsepower: 190,
            mass: 9074,
            max_speed: 22,
            brand: Brand.CASE_IH,
            orders: null,
        },
        {
            equipment_type: EquipmentType.HARVESTER,
            tyre_type: TyreType.R4,
            model: "TORUM 760",
            working_width: 12,
            cost_per_day: 3420.00,
            crop_capacity: 12000,
            fuel_capacity: 850,
            horsepower: 490,
            mass: 16142,
            max_speed: 32,
            brand: Brand.ROSTSELMASH,
            orders: null,
        },
        {
            equipment_type: EquipmentType.CULTIVATOR,
            model: "TERRANO 4 FX",
            working_width: 4,
            cost_per_day: 360.00,
            power_required: 160,
            mass: 2740,
            brand: Brand.HORSCH,
            orders: null,
        },
        {
            equipment_type: EquipmentType.CULTIVATOR,
            model: "CARRIER XL 625",
            working_width: 6,
            cost_per_day: 520.00,
            power_required: 260,
            mass: 6600,
            brand: Brand.VADERSTAD,
            orders: null,
        },
        {
            equipment_type: EquipmentType.CULTIVATOR,
            model: "TIGER 10 LT",
            working_width: 10,
            cost_per_day: 1040.00,
            power_required: 400,
            mass: 10835,
            brand: Brand.HORSCH,
            orders: null,
        },
        {
            equipment_type: EquipmentType.SOWING_MACHINE,
            model: "GL 420",
            capacity: 2740,
            working_width: 3,
            cost_per_day: 50.00,
            power_required: 120,
            mass: 2300,
            brand: Brand.GRIMME,
            orders: null,
        },
        {
            equipment_type: EquipmentType.SOWING_MACHINE,
            model: "RAPID A 600S",
            capacity: 3100,
            working_width: 6,
            cost_per_day: 150.00,
            power_required: 180,
            mass: 6000,
            brand: Brand.VADERSTAD,
            orders: null,
        },
        {
            equipment_type: EquipmentType.SOWING_MACHINE,
            model: "MAESTRO 12 SW",
            capacity: 9000,
            working_width: 9,
            cost_per_day: 330.00,
            power_required: 180,
            mass: 7175,
            brand: Brand.HORSCH,
            orders: null,
        },
        {
            equipment_type: EquipmentType.TIPPER,
            model: "DB 8",
            capacity: 8000,
            tyre_type: TyreType.R3,
            cost_per_day: 188.00,
            mass: 3541,
            brand: Brand.METALTECH,
            orders: null,
        },
        {
            equipment_type: EquipmentType.TIPPER,
            model: "AGROLINER TKD 302",
            capacity: 21000,
            tyre_type: TyreType.R3,
            cost_per_day: 540.00,
            mass: 4498,
            brand: Brand.KROEGER,
            orders: null,
        },
        {
            equipment_type: EquipmentType.TIPPER,
            model: "ASS  298",
            capacity: 47000,
            tyre_type: TyreType.R3,
            cost_per_day: 1220.00,
            mass: 7526,
            brand: Brand.FLIEGL,
            orders: null,
        },
    ]).execute();

}).catch(error => console.log(error));